# Generated by Django 4.2.16 on 2026-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField()),
                ('resolved_intent', models.CharField(max_length=100)),
                ('action_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('ambiguous', 'Ambiguous')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
