# Generated by Django 4.2.16 on 2026-06-25 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='macro',
            constraint=models.UniqueConstraint(fields=('user', 'trigger_phrase'), name='unique_trigger_per_user'),
        ),
    ]
